Move CategoryMerchandising util to php-sdk
Nosto/nosto-magento2-cmp pull request #143
Opened 2021-12-09 12:13 UTC by dairbuirabass

## Description
Moved CategoryMerchendasing utility from CMP to php-sdk module. PR: https://github.com/Nosto/nosto-php-sdk/pull/319

## Related Issue
Closes 136

## Motivation and Context
The functionality within utility is more suited to PHP-SDK module than CMP

## How Has This Been Tested?
Locally.

## Documentation:

## Checklist:
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] I have assigned the correct milestone or created one if non-existent.
- [x] I have correctly labeled this pull request.
- [x] I have linked the corresponding issue in this description.
- [ ] I have updated the corresponding Jira ticket.
- [x] I have requested a review from at least 2 reviewers
- [x] I have checked the base branch of this pull request
- [x] I have checked my code for any possible security vulnerabilities

2021-12-09 12:14 UTC, dairbuirabass commented
@olsi-qose Inspections fail due to parallel changes in the php-sdk module, what's best way to handle this?

2021-12-09 12:31 UTC, olsi-qose commented
> 

Make the changes in the PHP-SDK repo first and release them. Then bump the sdk dependency version here

2021-12-09 13:33 UTC, dairbuirabass commented
> > 
> 
> Make the changes in the PHP-SDK repo first and release them. Then bump the sdk dependency version here

https://github.com/Nosto/nosto-php-sdk/pull/319 here are the changes

2021-12-22 15:18 UTC, olsi-qose requested changes

2021-12-22 15:18 UTC, olsi-qose commented on Utils/CategoryMerchandising.php
>      const DISPATCH_EVENT_KEY_LIMIT = 'limit';
Move these constants to other classes, like Pre/PostRequestAction and delete this class

2021-12-27 08:20 UTC, olsi-qose approved these changes

2021-12-27 08:26 UTC, merged